# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

QUESTION_TEMPLATES = {
    "x_movement": [
        # No mention of explicit X-axis unless we define it inline.
        "Which way did the camera move horizontally, to the left or right?",
        "Please tell me if the camera moved left or right?",
        "Did the camera move left or right?",
        "Is the camera's horizontal shift toward the left or the right?",
        "Could you specify whether the camera moved left or right in the horizontal plane?",
        "Horizontally speaking, did the camera go in a leftward or rightward direction?",
        "Let me know if the camera shifted horizontally to the left or to the right?",
        "From the first image to the second, does the camera appear to have moved left or right?",
        "Is the camera horizontally offset to the left side or the right side compared to before?",
        "The first image is oriented such that positive X is to the right, Y is down, Z is forward. Given that, can you determine if the camera's motion was left or right along the X-axis?",
        "The first image is oriented such that positive X is to the right, Y is down, Z is forward. In terms of X movement, would you say the camera's displacement is left or right?",
        "Looking at the horizontal direction, is the camera's shift going left or right?",
        "Does the second view suggest a leftward or rightward movement in the scene?",
        "How would you describe the camera's horizontal shift: left or right?",
        "Between these two frames, is the camera more to the left or to the right now?",
        "If I track the camera, did it pan left or move right horizontally?",
        "Does the camera's new location suggest a leftward or rightward shift?",
        "Comparing the start and end, which horizontal direction does the camera favor?",
        "Is there a noticeable left or right displacement of the camera in the second shot?",
        "When you observe the images, does the camera appear to have gone left or right?",
        "Can you confirm if the horizontal motion is towards left or right from the original spot?",
        "Is the camera's final position horizontally left or horizontally right relative to where it started?",
        "Would you say the camera is drifting to the left side or the right side based on these views?",
        "From the vantage change, has the camera slid to the left or to the right?",
        "Comparing object overlaps, do you think the camera drifted left or drifted right?",
        "Looking at parallax, would the camera have moved left or right in the scene?",
        "Does the camera end up on the left side or right side in the second image, horizontally?",
        "Which horizontal direction best describes the camera's movement: left side or right side?",
        "What does the horizontal disparity suggest: a left move or a right move?",
        "Is the camera's final horizontal position on the left or the right compared to the original?"
    ],
    "y_movement": [
        # Similar approach: no explicit Y-axis mention unless defined.
        "Did the camera move upward or downward?",
        "Which vertical direction did the camera take: up or down?",
        "Could you tell if the camera shifted up or shifted down?",
        "Please describe whether the camera rose or dropped vertically?",
        "Is there an upward or downward displacement of the camera between these images?",
        "Does the camera appear to be higher or lower than before?",
        "From the first shot to the second, has the camera moved up or down in height?",
        "Looking at vertical change, is it an upward shift or a downward shift?",
        "Would you say the camera has elevated or descended vertically?",
        "Is the camera's vantage point now above or below its old position?",
        "Did the camera height increase (up) or decrease (down)?",
        "Comparing both images, is the camera's perspective higher or lower?",
        "Does the camera appear to have climbed upward or fallen downward between shots?",
        "Which way along the vertical plane does the camera move: up or down?",
        "Would you classify the camera's vertical movement as going up or going down?",
        "Is there a noticeable vertical lift or vertical drop of the camera?",
        "From this vantage, does it look like the camera ascended or descended?",
        "Is the camera vantage taller or shorter than it was, implying up or down motion?",
        "Let me know if the camera's new position is above or below the original one.",
        "Does the camera appear to have gone higher (up) or lower (down)?",
        "Looking at the alignment, is it clear if the camera ended up above or below its initial state?",
        "Between these frames, do we see a camera lift or a camera dip?",
        "Could you specify if the camera rose up or sank down?",
        "Observing the images, did the camera appear to tilt upward in location or downward?",
        "Did the camera move along a positive vertical direction or negative one?",
        "Is the camera vantage now elevated or depressed relative to its old vantage?",
        "Which direction does the vertical shift go: upward or downward?",
        "Does the final image show the camera in a higher plane or a lower plane?",
        "Is the camera's new vantage pointed from a higher angle or from a lower angle?",
        "Would you say the camera moved up or down along the vertical perspective?"
    ],
    "z_movement": [
        # No explicit Z-axis mention unless defined.
        "Did the camera move forward or backward in the scene?",
        "Which way along depth did the camera shift: forward or back?",
        "Would you say the camera advanced or retreated?",
        "Is there an approach (forward) or a withdrawal (backward) in camera movement?",
        "Please clarify if the camera stepped closer (forward) or further (back) from the subject?",
        "Does the camera appear to have moved in toward the objects or away from them?",
        "From the first position to the second, is the camera's movement forward or backward?",
        "Looking at the depth, did the camera push forward or pull back?",
        "In terms of distance to the scene center, has the camera decreased (forward) or increased (back)?",
        "Is the camera traveling deeper into the scene or moving out of it?",
        "Could you identify if there's a forward surge or a backward shift in the camera's vantage?",
        "Does the viewpoint suggest a forward stride or a backward retreat?",
        "Comparing both images, is the camera generally closer or farther away from the objects?",
        "Has the camera's new position advanced on the scene or receded from it?",
        "Would you classify the camera's move as an approach or a departure?",
        "Does it look like the camera stepped in or stepped out from its original spot?",
        "Is the distance from the camera to the background smaller (forward) or larger (back)?",
        "Please check if the camera is now nearer or farther than before?",
        "Viewing the overlap, do we see a forward approach or a backward shift?",
        "Has the camera come closer in the second image or does it appear more distant?",
        "Does the second frame indicate a push into the scene (forward) or a pull out (back)?",
        "If we consider the vantage, is it pushing in or pulling away from the center of the view?",
        "Is the camera moving in for a closer look or stepping away for a wider perspective?",
        "Would you note a negative shift (back) or positive shift (forward) in the depth direction?",
        "Does the camera's vantage in the second image appear more zoomed in (forward) or out (back)?",
        "Observing the scale of objects, does it indicate a forward movement or a backward one?",
        "Is the camera vantage more intimate (forward) or more distant (back)?",
        "Between these images, is the camera drifting toward or away from the scene?",
        "Considering the depth plane, does the camera shift in or out from the original viewpoint?",
        "Finally, how does the camera's position read: forward or backward along the scene's depth?"
    ],
    "yaw_movement": [
        # 9 with yaw definition
        "The yaw angle is the angle of the forward direction axis of the camera around the gravity axis, approximating left-right rotation. Did the camera rotate left or right in this movement?",
        "The yaw angle is the left-right rotation around the gravity axis. Could you identify if the camera rotates to the left side or the right side?",
        "The yaw angle is how the camera rotates horizontally around the gravity axis. Did we observe a leftward or rightward pivot?",
        "Yaw is the horizontal rotation around gravity. In this movement, did the camera turn left or right from the first image to the second?",
        "We define yaw as the left-right rotation about the gravity axis. Which direction does the camera rotate: left or right?",
        "Yaw refers to side-to-side rotation around the gravity axis. Are we seeing a left rotation or right rotation from image one to image two?",
        "By yaw, we mean a horizontal turn around the up-axis. Could you clarify if the camera rotates to the left or to the right?",
        "Yaw angle means left-right pivot around gravity. In this camera movement, does the camera rotate left or rotate right?",
        "Yaw is an angle describing the camera's rotation left or right around vertical. Please tell me if it pivoted left or pivoted right?",

        # 21 without definition
        "Did the camera rotate to the left or to the right side?",
        "Which direction does the camera pivot: left or right?",
        "Would you say there's a leftward rotation or a rightward rotation in the camera's vantage?",
        "Is the camera turning left or turning right from the first viewpoint to the second?",
        "Could you identify if the camera's movement is a left spin or a right spin around its vertical axis?",
        "Does the camera appear to revolve left or revolve right looking from above?",
        "In terms of rotation, do we see the camera pivoting left or pivoting right?",
        "Between these two frames, is the camera heading turned left or turned right?",
        "Has the camera orientation swung to the left side or to the right side?",
        "Which side does the camera now face after the rotation, left or right?",
        "Let me know if the camera's new orientation is angled left or angled right?",
        "Do you notice a left turn or a right turn in the camera's horizontal plane?",
        "Would you classify this rotation as turning left or turning right around the vertical axis?",
        "From the vantage changes, is the camera rotating left or rotating right horizontally?",
        "Has the camera's heading been adjusted left or right from the original viewpoint?",
        "Does the camera revolve left or revolve right around its upright axis?",
        "Observing the shift, does the lens pivot left or pivot right from the first shot to the second?",
        "Comparing the old and new orientation, is there a left swing or right swing in the camera's facing direction?",
        "In this scene, do we see a left turn or a right turn from the camera's perspective?",
        "Would you say the camera's horizontal rotation is left or is it right relative to its initial orientation?",
        "Finally, is the camera's horizontal pivot oriented left or oriented right after the movement?"
    ],
    # ------------------------------------------------------------------------
    #  pitch_movement (MODIFIED: 30 total, 9 mention definition, 21 do not)
    # ------------------------------------------------------------------------
    "pitch_movement": [
        # 9 with pitch definition
        "The pitch angle is the angle between the forward direction axis of the camera and the ground, approximating the up-down tilt. Did the camera rotate up or down?",
        "The pitch angle defines how the camera rotates vertically. Does the camera tilt upward or tilt downward in this movement?",
        "Pitch is the up-down rotation relative to the ground. Could you identify if the camera's pitch is rotating up or rotating down?",
        "We define pitch as the vertical pivot angle. Does the camera rotate upward or rotate downward from the first image to the second?",
        "Pitch indicates how the camera tilts up or down around a horizontal axis. Which direction does the camera rotate: up or down?",
        "By pitch angle, we refer to the camera's up-down rotation relative to the ground. Are we seeing an upward tilt or a downward tilt?",
        "Pitch is the up-down tilt measure for the camera. In this movement, does it rotate up or rotate down from the first viewpoint to the second?",
        "Considering pitch as vertical rotation, does the camera tilt up or tilt down in these frames?",
        "The pitch angle captures the camera's up-down pivot. Please tell me if it pivoted up or pivoted down?",

        # 21 without definition
        "Did the camera rotate upward or rotate downward?",
        "Which vertical rotation direction does the camera take: up or down?",
        "Would you say there's an upward tilt or a downward tilt in the camera's vantage?",
        "Is the camera pivoting up or pivoting down from the first viewpoint to the second?",
        "Could you identify if the camera's movement is an upward pitch or a downward pitch along its horizontal axis?",
        "Does the camera appear to revolve up or revolve down from the original angle?",
        "In terms of vertical rotation, do we see the camera pivoting up or pivoting down?",
        "Between these two frames, is the camera angled more upward or more downward?",
        "Has the camera orientation tilted to a higher angle or to a lower angle?",
        "Which direction does the camera now face vertically after the rotation, up or down?",
        "Let me know if the camera's new orientation is angled upward or angled downward?",
        "Do you notice an up tilt or a down tilt in the camera's vertical plane?",
        "Would you classify this rotation as tilting up or tilting down around the horizontal axis?",
        "From the vantage changes, is the camera rotating up or rotating down vertically?",
        "Has the camera's pitch been adjusted up or down from the original viewpoint?",
        "Does the camera revolve up or revolve down around its center axis?",
        "Observing the shift, does the lens pivot up or pivot down from the first shot to the second?",
        "Comparing the old and new orientation, is there an upward tilt or downward tilt in the camera's facing direction?",
        "In this scene, do we see an upward pitch or a downward pitch from the camera's perspective?",
        "Would you say the camera's vertical rotation is up or is it down relative to its initial orientation?",
        "Finally, is the camera's vertical pivot oriented up or oriented down after the movement?"
    ],
    "total_distance": [
        # No major changes needed, user said "overall_distance" is fine to keep as is.
        "How far did the camera travel between the two shots?",
        "What is the total distance the camera moved from its first position?",
        "Could you give me the magnitude of the camera's displacement?",
        "I'm curious about the overall traveled distance of the camera in millimeters?",
        "Please specify the camera's total movement distance.",
        "From start to end, how many units (mm) did the camera shift in space?",
        "What is the absolute distance covered by the camera between these images?",
        "Please provide the length of the path the camera took.",
        "Does the camera have a large or small travel distance, and how much is it?",
        "Could you measure the total displacement for the camera's movement?",
        "Could you calculate the overall distance from the first pose to the second?",
        "In numerical terms, how far did the camera go?",
        "Is there a measurement for the camera's complete travel distance in mm?",
        "Between these two viewpoints, what's the camera's movement distance?",
        "I want to know the total length of the camera's translation.",
        "Please share how many millimeters the camera has moved in total.",
        "Is the camera's movement more than a few millimeters, and how many exactly?",
        "How do you quantify the complete distance traveled by the camera?",
        "What is the final measure of the distance the camera traversed?",
        "How large is the gap between the camera's initial and final positions in mm?",
        "What's the camera's net travel distance from the first shot to the second shot?",
        "I'm interested in the point-to-point distance of the camera's shift.",
        "Could you give an estimate or exact number of how far the camera has moved?",
        "Does the data say how many millimeters separate the old position and the new position?",
        "What's the measurement of the camera's movement vector's length?",
        "Check the final distance: how many mm did the camera shift overall?",
        "In your analysis, what's the total movement distance for the camera?",
        "If we consider the start and end points, how far apart are they for the camera?",
        "Please clarify the total displacement distance in millimeters for the camera.",
        "Give me the final figure for the camera's traveled distance in mm?"
    ],
    "yaw_angle": [
        # 9 with yaw definition
        "The yaw angle is the angle of the forward direction axis of the camera around the gravity axis. It approximates the left-right rotation angle. How many degrees does the camera rotate horizontally?",
        "The yaw angle is the camera's horizontal rotation around the gravity axis. Could you specify in degrees how much it rotated left-right?",
        "Yaw is the left-right rotation measure around gravity. What is the numeric angle of this rotation in degrees?",
        "We define yaw angle as the horizontal pivot about the gravity axis. How many degrees does it rotate from the first pose to the second?",
        "The yaw angle captures left-right turning about vertical. Could you share the camera's yaw rotation in degrees?",
        "Yaw is the angle describing the camera's horizontal spin around gravity. How many degrees of rotation are we talking about?",
        "Given that yaw angle approximates left-right rotation, how large in degrees is the camera's yaw shift?",
        "Yaw angle means the measure of horizontal revolve. Please tell me how many degrees the camera rotates in yaw.",
        "By yaw angle, we refer to left-right rotation around the gravity axis. I'd like to know the camera's rotation in degrees.",

        # 21 without definition
        "How many degrees did the camera rotate horizontally from the first shot to the second?",
        "Could you specify the camera's horizontal rotation in degrees around the vertical axis?",
        "Please provide the numeric measure of the camera's left-right rotation in degrees.",
        "What is the exact horizontal turning angle (yaw) between the two images?",
        "I'm curious about how many degrees the camera has rotated side-to-side.",
        "Could you measure the camera's left-right spin in degrees for me?",
        "From the old orientation to the new, what's the camera's horizontal rotation angle in degrees?",
        "How much did the camera pivot around its upright axis, in degrees of rotation?",
        "Is the horizontal rotation small or large in degrees, and what's the actual value?",
        "Tell me the angle in degrees by which the camera turned horizontally.",
        "Could you approximate or exactly state the side-to-side rotation angle in degrees?",
        "In terms of left-right rotation, how many degrees does the camera revolve?",
        "Could you figure out the total horizontal rotation angle from one shot to another?",
        "I'm interested in the final numeric value of the horizontal rotation difference in degrees.",
        "What's the count of degrees the camera pivoted horizontally?",
        "Is there a measurement for the camera's horizontal turning in degrees you can share?",
        "Between the two poses, how big is the horizontal rotation in degrees?",
        "Could you check and give me the angle of horizontal rotation in degrees?",
        "How many degrees does the camera revolve side-to-side from its original orientation?",
        "Looking at the orientation, how many degrees of horizontal rotation do we detect from one image to the other?",
        "What's the net angle of horizontal rotation the camera has from the first pose to the second, in degrees?"
    ],
    # ------------------------------------------------------------------------
    #  pitch_angle (MODIFIED: 30 total, 9 mention definition, 21 do not)
    # ------------------------------------------------------------------------
    "pitch_angle": [
        # 9 with pitch definition
        "The pitch angle is the angle between the camera's forward direction axis and the ground, approximating up-down rotation. How many degrees did it rotate vertically?",
        "The pitch angle is the camera's up-down rotation relative to the ground. Could you specify in degrees how much it tilted?",
        "Pitch angle describes how the camera rotates vertically. What is the numeric measure in degrees?",
        "We define pitch angle as the vertical pivot about a horizontal axis. How many degrees does it move from the first pose to the second?",
        "Pitch is the angle capturing up-down spin. Could you share the camera's pitch rotation in degrees?",
        "The pitch angle approximates the camera's tilt around the horizontal. How many degrees of vertical rotation does it have?",
        "Given pitch is up-down rotation, how large in degrees is the camera's pitch shift from one image to the other?",
        "Pitch angle indicates the measure of vertical revolve. Please tell me how many degrees the camera tilts in pitch.",
        "By pitch angle, we refer to up-down rotation from the ground plane. I'd like to know the camera's rotation in degrees.",

        # 21 without definition
        "How many degrees did the camera rotate vertically from the first shot to the second?",
        "Could you specify the camera's vertical rotation in degrees around the horizontal axis?",
        "Please provide the numeric measure of the camera's tilt in degrees up or down.",
        "What is the exact vertical turning angle (pitch) between the two images?",
        "I'm curious about how many degrees the camera has tilted top to bottom.",
        "Could you measure the camera's up-down spin in degrees for me?",
        "From the old orientation to the new, what's the camera's vertical rotation angle in degrees?",
        "How much did the camera pivot around its side axis, in degrees of tilt?",
        "Is the vertical rotation small or large in degrees, and what's the actual value?",
        "Tell me the angle in degrees by which the camera turned vertically.",
        "Could you approximate or exactly state the up-down rotation angle in degrees?",
        "In terms of pitch, how many degrees does the camera revolve vertically?",
        "Could you figure out the total vertical rotation angle from one shot to another?",
        "I'm interested in the final numeric value of the vertical rotation difference in degrees.",
        "What's the count of degrees the camera pivoted up or down?",
        "Is there a measurement for the camera's vertical turning in degrees you can share?",
        "Between these two poses, how big is the vertical rotation in degrees?",
        "Could you check and give me the angle of vertical rotation in degrees?",
        "How many degrees does the camera revolve up-down from its original orientation?",
        "Looking at the orientation, how many degrees of vertical rotation do we detect from one image to the other?",
        "What's the net angle of vertical rotation the camera has from the first pose to the second, in degrees?"
    ],
    "displacement_vector": [
        "The first image is oriented such that positive X is right, Y is down, and Z is forward. What is the overall displacement vector of the camera's movement?",
        "The first image is oriented such that positive X is right, Y is down, and Z is forward. Could you provide the camera's movement vector in 3D coordinates?",
        "The first image is oriented with X->right, Y->down, Z->forward. Please specify the `[ x , y , z ]` displacement vector of the camera in mm?",
        "The first image sets X=right, Y=down, Z=forward as positive. I'm curious about the entire translation vector from the first to second position.",
        "Given X->right, Y->down, Z->forward, what does the camera's shift vector look like in millimeters for each axis?",
        "We define X as right, Y as down, Z as forward. How do you represent the 3D displacement of the camera as a vector?",
        "Considering the first image orientation (X=right, Y=down, Z=forward), could you express the camera movement as a coordinate vector in mm?",
        "The first image uses positive X=right, Y=down, Z=forward. From the start to the end, what's the `[ x , y , z ]` translation of the camera?",
        "With X=right, Y=down, Z=forward, I want the camera's movement in vector form, specifying the offsets in each axis.",
        "Remember X->right, Y->down, Z->forward. Please give me the exact displacement as `[ x , y , z ]` in mm.",
        "The coordinate system is X=right, Y=down, Z=forward. Do we have the final 3D translation vector for the camera's shift?",
        "We assume positive X=right, Y=down, Z=forward. How can we break down the camera's movement into x, y, z components in mm?",
        "The first image orientation sets X, Y, Z as right, down, forward. Which vector best describes the camera's overall translation?",
        "Using X=right, Y=down, Z=forward, could you detail the camera's movement vector so I see how it moved along each axis?",
        "Positive X is right, Y is down, Z is forward. Is there a coordinate triple representing the camera's new position minus the old?",
        "If we consider X=right, Y=down, Z=forward, tell me the displacement vector that sums up how the camera traveled in `[ x , y , z ]` mm.",
        "The coordinate definition is X->right, Y->down, Z->forward. What's the resulting 3D vector for the camera's net translation?",
        "In a system where X=right, Y=down, Z=forward, I'd like the translation vector: `[ x_movement , y_movement , z_movement ]` in mm.",
        "Given the orientation X=right, Y=down, Z=forward, does the data give us the camera's movement as a standard `[ x , y , z ]` vector?",
        "From the start to end, with X=right, Y=down, Z=forward, what's the `[ x , y , z ]` vector describing the camera translation?",
        "Under the assumption X=right, Y=down, Z=forward, I want the final movement as a three-dimensional vector describing its translation.",
        "Taking X=right, Y=down, Z=forward as the scene basis, how do we express the total movement as `[ x , y , z ]` in mm?",
        "If the first image orientation is X=right, Y=down, Z=forward, could you share the numeric triple for the camera's displacement along `[ x , y , z ]`?",
        "We define X=right, Y=down, Z=forward. I'm looking for the final movement as a `[ x , y , z ]` vector for the camera.",
        "Between these images, using X=right, Y=down, Z=forward, what's the vector that the camera traveled in mm?",
        "The coordinate system is X=right, Y=down, Z=forward. Is there a 3D vector capturing the net offset from the original spot?",
        "In the orientation where X=right, Y=down, Z=forward, how do we write the camera's translation in the form `[ x_offset , y_offset , z_offset ]` mm?",
        "Assuming the first image sets X=right, Y=down, Z=forward, check the final difference in each axis-this forms a vector for the camera movement, correct?",
        "Given X=right, Y=down, Z=forward, I'd like you to list the camera's total displacement vector `[ x , y , z ]` in mm.",
        "The first image orients X->right, Y->down, Z->forward. Please specify that vector showing exactly how the camera moved in all three dimensions."
    ]
}

TASK_DESCRIPTION = [
    "Image-1: <image>\nImage-2: <image>\nGiven two images, analyze the movements of the cameras that captured them. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nEvaluate how the camera has moved between these two images. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nObserve and describe the camera's motion from one image to the other. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nDetermine the change in camera viewpoint across these two images. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nExamine how the camera shifted its position/orientation between these shots. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nIdentify the differences in camera pose when comparing these images. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nAnalyze the changes in the camera's placement and angle between the two frames. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nExplain how the camera transitioned from the first viewpoint to the second. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nCompare these images to infer the camera's motion. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
    "Image-1: <image>\nImage-2: <image>\nPinpoint the camera's shift in position and rotation between the two pictures. The movement should be relative to the first image. Note that the objects in the images are assumed to be static.",
]

ANSWER_TEMPLATES = {
    "x_movement": [
        "The camera shifted `{x_movement}`.",
        "It shows a noticeable move `{x_movement}` along the horizontal axis.",
        "There's a clear `{x_movement}` displacement when comparing both images.",
        "From the first image to the second, the camera moved `{x_movement}` horizontally.",
        "Observation reveals a `{x_movement}` translation in the camera's vantage.",
        "Overall, the camera travels `{x_movement}` in the horizontal direction.",
        "A side-to-side shift can be described as `{x_movement}`.",
        "Relative to its initial position, the camera is displaced `{x_movement}` horizontally.",
        "We confirm the camera went `{x_movement}` along the horizontal plane.",
        "The camera's movement is best described as `{x_movement}`."
    ],
    "y_movement": [
        "The camera shifted `{y_movement}` vertically.",
        "It exhibits a noticeable move `{y_movement}` along the vertical axis.",
        "There's a `{y_movement}` displacement in the camera's height between images.",
        "From the first image to the second, the camera moved `{y_movement}` in elevation.",
        "We observe a `{y_movement}` translation when comparing the two shots.",
        "Overall, the camera travels `{y_movement}` along the vertical dimension.",
        "Clearly, there's an up/down shift characterized as `{y_movement}`.",
        "Relative to its starting point, the camera is now `{y_movement}` in height.",
        "We see the camera going `{y_movement}` along the vertical plane.",
        "The camera's movement is best described as `{y_movement}` in the vertical sense."
    ],
    "z_movement": [
        "The camera shifted `{z_movement}` in depth.",
        "It demonstrates a noticeable move `{z_movement}` along the forward-backward axis.",
        "A `{z_movement}` displacement is evident when examining both images.",
        "Comparing the frames, the camera moved `{z_movement}` with respect to scene depth.",
        "We detect a `{z_movement}` translation from the first image to the second.",
        "Overall, the camera travels `{z_movement}` in the forward/backward direction.",
        "It's clear there's a depth-wise shift described as `{z_movement}`.",
        "The camera progressed `{z_movement}` along the scene's forward axis.",
        "The camera moved `{z_movement}` in depth.",
        "Relative to its initial spot, the camera moved `{z_movement}` in depth.",
    ],
    "yaw_movement": [
        "The camera rotated `{yaw_movement}` around the vertical axis.",
        "It shows a notable yaw rotation of `{yaw_movement}`.",
        "We observe a `{yaw_movement}` pivot from the first image to the second.",
        "Clearly, there's a left-right spin described as `{yaw_movement}`.",
        "Relative to its initial orientation, the camera turned `{yaw_movement}`.",
        "From a top view, the camera appears to rotate `{yaw_movement}` horizontally.",
        "We confirm the camera has undergone a `{yaw_movement}` yaw rotation.",
        "The camera's horizontal rotation is best described as `{yaw_movement}`.",
        "The lens direction changed by rotating `{yaw_movement}` side-to-side.",
        "The camera pivoted `{yaw_movement}` in yaw."
    ],
    "pitch_movement": [
        "The camera tilted `{pitch_movement}` around the horizontal axis.",
        "It shows a notable pitch rotation of `{pitch_movement}`.",
        "We observe a `{pitch_movement}` vertical pivot between these frames.",
        "There's a clear up-down spin described as `{pitch_movement}`.",
        "Relative to the initial tilt, the camera moved `{pitch_movement}` in pitch.",
        "Considering vertical rotation, the camera has tilted `{pitch_movement}`.",
        "We confirm the camera exhibits a `{pitch_movement}` pitch rotation.",
        "The camera's vertical rotation is `{pitch_movement}`.",
        "The lens angle changed by tilting `{pitch_movement}`.",
        "The camera pivoted `{pitch_movement}` in pitch."
    ],
    "total_distance": [
        "The camera traveled a total of `{total_distance}` mm.",
        "In total, the camera displacement amounts to `{total_distance}` mm.",
        "Overall, it covers about `{total_distance}` mm from start to finish.",
        "Comparing both images, the camera moved roughly `{total_distance}` mm in distance.",
        "We see a net travel of `{total_distance}` mm for the camera.",
        "The total distance covered by the camera is `{total_distance}` mm.",
        "The camera's translation spans `{total_distance}` mm.",
        "The final measure of movement is `{total_distance}` mm.",
        "The complete shift in position is `{total_distance}` mm.",
        "The camera's overall distance of travel is `{total_distance}` mm."
    ],
    "yaw_angle": [
        "It rotated `{yaw_angle}` degrees horizontally.",
        "We note a yaw change of `{yaw_angle}` degrees.",
        "The camera's left-right rotation measures about `{yaw_angle}` degrees.",
        "Observations indicate a yaw rotation of `{yaw_angle}` degrees.",
        "The horizontal turning angle sums to `{yaw_angle}` degrees.",
        "The camera's yaw shift is `{yaw_angle}` degrees in total.",
        "From the initial orientation, the camera pivoted `{yaw_angle}` degrees around vertical.",
        "We detect a rotation of `{yaw_angle}` degrees in the horizontal plane.",
        "There's a `{yaw_angle}`-degree difference in the camera's yaw.",
        "The camera has a yaw angle change of `{yaw_angle}` degrees."
    ],
    "pitch_angle": [
        "It tilted `{pitch_angle}` degrees vertically.",
        "We note a pitch change of `{pitch_angle}` degrees.",
        "The camera's up-down rotation measures about `{pitch_angle}` degrees.",
        "Observations indicate a pitch rotation of `{pitch_angle}` degrees.",
        "The vertical turning angle sums to `{pitch_angle}` degrees.",
        "Hence, the camera's pitch shift is `{pitch_angle}` degrees in total.",
        "From the initial orientation, the camera pivoted `{pitch_angle}` degrees around horizontal.",
        "We detect a rotation of `{pitch_angle}` degrees in the vertical plane.",
        "There's a `{pitch_angle}`-degree difference in the camera's pitch.",
        "The camera has a pitch angle change of `{pitch_angle}` degrees."
    ],
    "displacement_vector": [
        "The displacement vector is `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "Summarily, the camera's movement vector is `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "Its translation can be described by `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "The overall shift is `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "We can represent its movement as `[ {x_value} , {y_value} , {z_value} ]` mm in 3D space.",
        "Comparing both positions, the net translation vector is `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "From start to end, the camera's displacement is `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "The final vector describing the camera's movement is `[ {x_value} , {y_value} , {z_value} ]` mm.",
        "We have `[ {x_value} , {y_value} , {z_value} ]` mm as the shift.",
        "The camera's total 3D movement is `[ {x_value} , {y_value} , {z_value} ]` mm."
    ]
}
